#!/bin/bash
# skips source control metadata folders and hidden files (.*)

FOLDERS="src"

# format C++ code
for dir in $FOLDERS;
do
  find $dir ! -type d -not \( -name ".*" \) -a \( -name \*.cpp -o -name \*.h -o -name \*.inc \) | uncrustify -c uncrustify.cfg -F - -l CPP --replace --no-backup
done

# format C code
for dir in $FOLDERS;
do
  find $dir ! -type d -not \( -name ".*" \) -a \( -name \*.c \) | uncrustify -c uncrustify.cfg -F - -l C --replace --no-backup
done
